bundler_args: ""
language: ruby
gemfile:
  - spec/gemfiles/32.gemfile
  - spec/gemfiles/40.gemfile
  - spec/gemfiles/41.gemfile
  - spec/gemfiles/42.gemfile
rvm:
  - 1.9.3
  - 2.1.4
matrix:
  exclude:
script: bundle exec rake spec

addons:
  postgresql: "9.3"

services:
  - redis-server

before_script:
  - psql -c 'create database "canvas-jobs-test-1";' -U postgres

env:
  - TEST_DB_USERNAME=postgres
